name: build

description: caller workflow
inputs:
  username:
    required: true
  runs-on: workflow-call
runs:
  using: "composite"

secrets:
  JF_KEY:
    required: true
  
jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: |
          echo "secret key is ${{ secrets.JF_KEY }}"
          echo The username is ${{ inputs.username }}
          echo f"Welcome $${{ inputs.username }}"
