name: build
description: composite actions
inputs:
  username:
    required: true
  JF_KEY:
    required: true

runs:
  using: "composite"
     
  steps:
    shell: powershell    
  - name: Run a one-line script
    uses: actions/checkout@v4

  - name: Print the input name to STDOUT
    run: |
      echo secret key is ${{ inputs.JF_KEY }}
      echo The username is ${{ inputs.username }}
      echo f"Welcome $${{ inputs.username }}"
      if [ ${{ inputs.JF_KEY }} == "whoami" ]
      then
          echo "Successfully retrived secret key as input"
      fi                          