name: "Main-Action"
on:
    workflow_dispatch:
        inputs:
            username:
                description: "Hello to You Name Please!"
                required: true
                default: "Venkat N"
      
jobs:
    tests:
        uses: ./.github/workflows/composite-actions/action.yml
        secrets: inherit
        with:
            username: "${{ github.events.inputs.username }}"                

    builds:
        runs-on: ubuntu-latest
        steps:
          - name: Run a one-line script
            uses: actions/checkout@v4
            env:
                JF_KEY: "${{ secrets.JF_KEY }}"