name: "Main-Action"
on:
    workflow_dispatch:
        inputs:
            username:
                description: "Hello to You Name Please!"
                required: true
                default: "Venkat N"
      
jobs:
    tests:
        uses: ./.github/workflows/composite-actions/build.yml@master
        secrets: inherit
        with:
            username: ${{ github.event.inputs.username}} 

    builds:
        runs-on: ubuntu-latest
        steps:
          - name: Run a one-line script
            uses: actions/checkout@v4
            env:
                JF_KEY: ${{ secrets.GITHUB_TOKEN }}