name: "Main-Action"
on:
    workflow_dispatch:
        inputs:
            UserName:
                description: "Hello to You Name Please!"
                required: true
                default: "Venkat N"
      
jobs:
    build:
        runs-on: Windows
        steps:
          - name: Call Resuable Workflow
            uses: ./github/workflow/.action.yml
            
