name: "Main Composite Action"
on:
    workflow_dispatch: 
        inputs:
            username:
                description: "Hello to You Name Please!"
                required: true
                default: "Venkat N"
jobs:
    build:
        runs-on: ubuntu-latest   
        steps:
          - name: Checking out
            uses: actions/checkout@v4

    process: 
        runs-on: ubuntu-latest   
        steps:
          - name: Checking out
            uses: actions/checkout@v4

          - name: Calling composite action to run
            uses: ./.github/workflows/composite-actions
            with:
                JF_KEY: ${{ secrets.JF_KEY }}
                username: ${{ inputs.username }}
                